# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # Specify the GitHub environment
    environment: ${{ vars.ENVIRONMENT }}
    # The type of runner that the job will run on
    runs-on: self-hosted
    env:
      # Instruct the AzureRM provider to use the managed identity.
      ARM_USE_MSI: "true"
      # Passing a normal variable:
      TF_VAR_environment: ${{ vars.ENVIRONMENT }}
      # Passing a secret (make sure this secret is set in your repository or organization):
      TF_VAR_subscription_id: ${{ secrets.SUBSCRIPTION_ID }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Azure Login with Managed Identity
        # This will use the managed identity from the VM
        run: az login --identity
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world! ${{ vars.ENVIRONMENT }} ${{ secrets.SUBSCRIPTION_ID }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # Test tf code
      - name: Run plan
        run: |
          terraform init -backend-config="./environment/prod/backend.config"
          terraform plan

      # Terraform apply
      - name: Terraform Apply
        run: terraform apply -auto-approve #-backend-config="./environment/${{ vars.ENVIRONMENT }}/backend.config"
